### ISSUE TITLE
include option to run `npm pack` prior to `npm publish`

### ISSUE THREAD

**Issue by jgravois** [ngoldman/gh-release#38]
@kneemer and i just published three bad npm versions of Leaflet.shapeMarkers before she realized that we needed to include a `.npmignore` file in our project to ensure the .zip asset included in the package unpacked back into a `dist` folder and was **not** just lumped on as a raw zipped file.

here's the error our release script was throwing:
```
npm ERR! registry error parsing json
+ leaflet-shape-markers@1.0.2
```
this got me thinking that including a step in the release process which allows people to inspect the contents of `npm pack` might save boneheads like me from publishing non-overwritable versions on npm itself.

**Comment by bcomnes** [comment]
I like it :+1:

**Comment by ngoldman** [comment]
@jgravois How do you imagine this working in terms of the CLI?

**Comment by kneemer** [comment]
@ngoldman when you do a dry-run do you get a tarball of what would have been published like npm pack does?  I could see it being useful in that scenario.

**Comment by ngoldman** [comment]
@kneemer no, the `--dry-run` option just exits after previewing the release (see [bin/cli.js#L73](https://github.com/ngoldman/gh-release/blob/2ff6affadf9eec015db226e0f0b7894e4f6ec030/bin/cli.js#L73)).

`gh-release` never runs `npm publish` (it doesn't interact with `npm` at all). I'm not sure this something that `gh-release` needs to handle directly. @paulcpederson do you have any insight on this one since you're the author of [`gh-release-assets`](https://github.com/paulcpederson/gh-release-assets)?

**Comment by kneemer** [comment]
@ngoldman sorry, I misunderstood what was happening here :virgo:

**Comment by jgravois** [comment]
> `gh-release` ... doesn't interact with `npm` at all).

my apologies.  if i had dug deeper into our own release script i would have seen that we are calling `npm publish` manually **after** running `gh-release`.

as it stands, my suggestion is *well* beyond the scope of this package.

**Comment by ngoldman** [comment]
:+1: no problem, it's still a good thing to think about. we dreamed of wrapping gh-release, build processes, and npm publish into [versioneer](https://github.com/ngoldman/versioneer) a long time ago as an alternative to bash script releases for cases like this.
